# Generated by Django 4.1.7 on 2023-03-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.UniqueConstraint(fields=('name_q', 'date'), name='ДЭЭЭЭЭЭЭ'),
        ),
    ]
