# Generated by Django 4.1.7 on 2023-03-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chart',
            constraint=models.CheckConstraint(check=models.Q(('dcount__gte', 0), ('dcount__lte', 24)), name='qwEWQ'),
        ),
    ]
