# Generated by Django 4.1.7 on 2023-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_chart_unique_together_chart_дэээээээ'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='dcount',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
