# Generated by Django 4.1.7 on 2023-03-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_squashed_0003_chart_dcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'ordering': ['date'], 'verbose_name': 'График', 'verbose_name_plural': 'Графики'},
        ),
    ]
